title: NURUL SYAFIQAH BINTI AHMAD
logo: https://kamansor.github.io/demo-cv1/Contoh Resume.jpg
description: |
  Casual Retail Sales Assistant\
  CONTACT\
  ADDRESS:\
    No 3, Lorong Syed Sheh, Kampung Jerai, 09200 Kupang, Baling Kedah.\
  PHONE:\
    011-36010237\
  EMAIL:\
    syafiqahahmad9798@gmail.com\
theme: jekyll-theme-minimal
